// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syusqcaslrxdkwaqsdks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5dXNxY2FzbHJ4ZGt3YXFzZGtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTc1MjgsImV4cCI6MjA3NDQ5MzUyOH0.LRh5wNTis6X7bJRMYvzvVEc3ytjjM6wQAM3oYHKd2Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});